### ISSUE TITLE
When re-directing user to Data Hub UI, open a new tab 

### ISSUE THREAD

**Issue by rahulbist** [uktrade/enquiry-mgmt-tool#45]
When re-directing user to Data Hub UI to search against the DNB dataset via the link "I still can't find what I'm looking for", the user should be re-directed to Data Hub UI through a new tab opening.

Currently when clicking "I still can't find what I'm looking for", Data Hub UI is opened on the current window which causes usability issues

**Comment by hnryjmes** [comment]
This has now been updated on the Company Search PR:
https://github.com/uktrade/enquiry-mgmt-tool/pull/37

This is actually somewhat controversial among frontend devs, with some fiercely believing that the default behaviour of the web is that links always open in the same tab and that the user should always have to choose to open in a new tab - even if you are leaving the site. I lean towards disagreeing, but as a compromise some sites choose to have an icon.

See discussion here for more info:
[Removing the external link icon from GOV.UK](https://designnotes.blog.gov.uk/2016/11/28/removing-the-external-link-icon-from-gov-uk/)
[When to use target=”_blank”](https://css-tricks.com/use-target_blank/)

**Comment by paulgain** [comment]
GDS advise against opening content in a new tab/window, however, there are some exceptions: https://twitter.com/GDSTeam/status/983992989650423809

The W3C mention _"warning before automatically opening a new window or tab"_
https://www.w3.org/TR/WCAG20-TECHS/G201.html#G201-description

**Comment by web-bert** [comment]
I agree with the point from @paulgain above:
> It is best practice that links do not open in new windows/tabs, unless the user is in the middle of a transaction

Unless the user is in the middle of a transaction, where they might need to look at a different site for some additional information to help complete their transaction and it is not easy for them to go back using the browser back button, then a link should be a normal link - otherwise we'd be opening tabs all the time which is just a jarring experience for users. I'd argue a most users know how to get a link opened in a new tab, so it should be a choice they make and not dictated to them.

**Comment by rahulbist** [comment]
@hnryjmes @paulgain @web-bert 

At the stage where we direct the user to Data Hub UI, this occurs when the user is currently modifying/updating a form. 

Therefore, if the user is required to go onto the Data Hub UI, we will need it to be opened on a new tab otherwise there changes could be lost.

**Comment by rahulbist** [comment]
Closing as this is no longer an issue
